# Generated by Django 5.1.7 on 2025-03-12 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weatherdata_city_alter_weatherdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
